name: Build

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3

      - uses: ./.github/actions/docker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
