name: Build & Publish
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: 0 2 * * *
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: ./.github/actions/docker
        with:
          push: true
          token: ${{ secrets.GITHUB_TOKEN }}
